name: Build & Test & Release

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  BuildTestRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          build-args: |
            ALPINE_VERSION=3.18
          tags: treezio/wkhtmltopdf:latest
      - name: Test WKHTMLtoPDF binary
        run: |
          docker run --rm treezio/wkhtmltopdf:latest wkhtmltopdf --log-level none https://www.google.es output.pdf
      - name: Copy binary
        uses: shrink/actions-docker-extract@v2
        id: extract
        with:
          image: treezio/wkhtmltopdf:latest
          path: /bin/wkhtmltopdf
      - name: Upload Binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: wkhtmltopdf-binary
          path: ${{ steps.extract.outputs.destination }}
      - name: Release Binary
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.extract.outputs.destination }}
          token: ${{ secrets.GITHUB_TOKEN }}
