name: build

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          push: false
          build-args: |
            ALPINE_VERSION=3.18
          tags: treezio/wkhtmltopdf:latest
      - uses: shrink/actions-docker-extract@v2
        id: extract
        with:
          image: treezio/wkhtmltopdf:latest
          path: /bin/wkhtmltopdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.extract.outputs.destination }}